package com.longlive.sikuli.gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.imageio.ImageIO;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.lang.reflect.UndeclaredThrowableException;
import java.util.Objects;

/**
 * @author 李威
 * @description
 * @date 2022/10/30 0:50
 */
public class yysMain {
    private JPanel JPanel;
    private JLabel JLabel;
    private JTextField text;
    private JButton button;
    private JLabel count;
    private JTextField loacation;


    public yysMain() {
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                String inputText = text.getText();

                /// 弹出框
                JDialog jDialog = new JDialog();
                // 设置相对位置. null代表位于屏幕居中
                jDialog.setLocationRelativeTo(null);
                // 设置标题
                jDialog.setTitle("Information");
                // 设置可见性
                jDialog.setVisible(true);
                // 设置大小
                jDialog.setSize(200, 200);
                // 设置弹出框图标
                try {
                    InputStream inputStream = Objects.requireNonNull(yysMain.class.getResourceAsStream("/images/rats.jpg"));
                    jDialog.setIconImage(ImageIO.read(inputStream));
                } catch (Exception exc) {
                    throw new UndeclaredThrowableException(exc);
                }

                // 给弹出框面板添加组件
                Container contentPane = jDialog.getContentPane();
                contentPane.add(new JLabel("hello~ " + inputText));
            }
        });
    }

    public static void main(String[] args) throws IOException {
        JFrame frame = new JFrame("yysMain");
        frame.setContentPane(new yysMain().JPanel);
        frame.setBounds(0, 0, 200, 200);
        frame.setLocationRelativeTo(null);
        frame.setTitle("痒痒鼠护肝助手");
        frame.setIconImage(ImageIO.read(Objects.requireNonNull(yysMain.class.getResourceAsStream("/images/rats.jpg"))));
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        JPanel = new JPanel();
        JPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        JLabel = new JLabel();
        JLabel.setText("次数");
        JPanel.add(JLabel, new GridConstraints(1, 0, 2, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        text = new JTextField();
        text.setText("");
        JPanel.add(text, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        button = new JButton();
        button.setHorizontalAlignment(0);
        button.setText("Button");
        button.setToolTipText("");
        JPanel.add(button, new GridConstraints(0, 2, 3, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        count = new JLabel();
        count.setText("图片路径");
        JPanel.add(count, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        loacation = new JTextField();
        JPanel.add(loacation, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return JPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }
}
